apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    backstage.io/kubernetes-id: nginx-sample-app
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        backstage.io/kubernetes-id: nginx-sample-app
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80

