apiVersion: v1
kind: Service
metadata:
  labels:
    backstage.io/kubernetes-id: nginx-sample-app
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

